# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Assembly/start_assembly.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Assembly(object):
    def setupUi(self, Assembly):
        Assembly.setObjectName("Assembly")
        Assembly.resize(1562, 714)
        self.centralwidget = QtWidgets.QWidget(Assembly)
        self.centralwidget.setObjectName("centralwidget")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(1410, 610, 131, 31))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 151, 41))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 80, 411, 271))
        self.listWidget.setObjectName("listWidget")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(40, 400, 141, 41))
        self.commandLinkButton.setStyleSheet("font: 57 12pt \"Ubuntu\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Icons/scan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(40, 440, 271, 41))
        self.commandLinkButton_3.setStyleSheet("font: 57 12pt \"Ubuntu\";")
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(40, 480, 271, 41))
        self.commandLinkButton_4.setStyleSheet("font: 57 12pt \"Ubuntu\";")
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_5.setGeometry(QtCore.QRect(40, 520, 271, 41))
        self.commandLinkButton_5.setStyleSheet("font: 57 12pt \"Ubuntu\";")
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 410, 89, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Icons/done_black_2048x2048.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 450, 89, 25))
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 490, 89, 25))
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 530, 89, 25))
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(19, 79, 411, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        Assembly.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Assembly)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1562, 22))
        self.menubar.setObjectName("menubar")
        self.menuConnection = QtWidgets.QMenu(self.menubar)
        self.menuConnection.setObjectName("menuConnection")
        self.menuDescription = QtWidgets.QMenu(self.menubar)
        self.menuDescription.setObjectName("menuDescription")
        self.menuAssembly_Status = QtWidgets.QMenu(self.menubar)
        self.menuAssembly_Status.setObjectName("menuAssembly_Status")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Assembly.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(Assembly)
        self.toolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar.setObjectName("toolBar")
        Assembly.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionUser = QtWidgets.QAction(Assembly)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Icons/login-background-images-clipart-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUser.setIcon(icon2)
        self.actionUser.setObjectName("actionUser")
        self.menubar.addAction(self.menuConnection.menuAction())
        self.menubar.addAction(self.menuDescription.menuAction())
        self.menubar.addAction(self.menuAssembly_Status.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionUser)

        self.retranslateUi(Assembly)
        QtCore.QMetaObject.connectSlotsByName(Assembly)

    def retranslateUi(self, Assembly):
        _translate = QtCore.QCoreApplication.translate
        Assembly.setWindowTitle(_translate("Assembly", "Assembly"))
        self.commandLinkButton_2.setText(_translate("Assembly", "Continue to tests"))
        self.label.setText(_translate("Assembly", "    Available Modules:"))
        self.commandLinkButton.setText(_translate("Assembly", "Scan Module"))
        self.commandLinkButton_3.setText(_translate("Assembly", "Set Module Location on the Dee"))
        self.commandLinkButton_4.setText(_translate("Assembly", "Set Optical Group"))
        self.commandLinkButton_5.setText(_translate("Assembly", "Set Power Group"))
        self.pushButton.setText(_translate("Assembly", "Done"))
        self.pushButton_2.setText(_translate("Assembly", "Done"))
        self.pushButton_3.setText(_translate("Assembly", "Done"))
        self.pushButton_4.setText(_translate("Assembly", "Done"))
        self.menuConnection.setTitle(_translate("Assembly", "Connection"))
        self.menuDescription.setTitle(_translate("Assembly", "Description"))
        self.menuAssembly_Status.setTitle(_translate("Assembly", "Assembly Status"))
        self.menuSettings.setTitle(_translate("Assembly", "Settings"))
        self.menuHelp.setTitle(_translate("Assembly", "Help"))
        self.toolBar.setWindowTitle(_translate("Assembly", "toolBar"))
        self.actionUser.setText(_translate("Assembly", "User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Assembly = QtWidgets.QMainWindow()
    ui = Ui_Assembly()
    ui.setupUi(Assembly)
    Assembly.show()
    sys.exit(app.exec_())
